// Static reference list of S&P 500 constituents — a snapshot, not live
// data (see the disclaimer on app/sp500/page.js). Sourced and cross-verified
// from two independent public datasets, not recited from memory:
//   - Ticker / name / GICS sector: a daily-updated scrape of Wikipedia's
//     "List of S&P 500 companies" (snapshot dated 2026-08-20).
//   - Market-cap ranking (for `tier`): stockanalysis.com's S&P 500 table,
//     fetched 2026-09-04. Both datasets cross-matched with zero mismatches
//     across all 503 tickers.
// tier: "mega" (>= $200B, top 59) | "large" ($15B-$200B, 382) | "mid" (< $15B,
// the tail of the index, 62) — no "small" tier, since the S&P 500 is
// structurally almost all large/mega cap by its own selection criteria.
export const SP500_LAST_UPDATED = "2026-09-04";

export const SP500_COMPANIES = [
  { ticker: "A", name: "Agilent Technologies", sector: "Health Care", tier: "large" },
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", tier: "mega" },
  { ticker: "ABBV", name: "AbbVie", sector: "Health Care", tier: "mega" },
  { ticker: "ABNB", name: "Airbnb", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "ABT", name: "Abbott Laboratories", sector: "Health Care", tier: "large" },
  { ticker: "ACGL", name: "Arch Capital Group", sector: "Financials", tier: "large" },
  { ticker: "ACN", name: "Accenture", sector: "Technology", tier: "large" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", tier: "large" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology", tier: "large" },
  { ticker: "ADM", name: "Archer Daniels Midland", sector: "Consumer Staples", tier: "large" },
  { ticker: "ADP", name: "Automatic Data Processing", sector: "Industrials", tier: "large" },
  { ticker: "ADSK", name: "Autodesk", sector: "Technology", tier: "large" },
  { ticker: "AEE", name: "Ameren", sector: "Utilities", tier: "large" },
  { ticker: "AEP", name: "American Electric Power", sector: "Utilities", tier: "large" },
  { ticker: "AES", name: "AES Corporation", sector: "Utilities", tier: "mid" },
  { ticker: "AFL", name: "Aflac", sector: "Financials", tier: "large" },
  { ticker: "AIG", name: "American International Group", sector: "Financials", tier: "large" },
  { ticker: "AIZ", name: "Assurant", sector: "Financials", tier: "mid" },
  { ticker: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financials", tier: "large" },
  { ticker: "AKAM", name: "Akamai Technologies", sector: "Technology", tier: "large" },
  { ticker: "ALB", name: "Albemarle Corporation", sector: "Materials", tier: "mid" },
  { ticker: "ALGN", name: "Align Technology", sector: "Health Care", tier: "mid" },
  { ticker: "ALL", name: "Allstate", sector: "Financials", tier: "large" },
  { ticker: "ALLE", name: "Allegion", sector: "Industrials", tier: "mid" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", tier: "mega" },
  { ticker: "AMCR", name: "Amcor", sector: "Materials", tier: "large" },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", tier: "mega" },
  { ticker: "AME", name: "Ametek", sector: "Industrials", tier: "large" },
  { ticker: "AMGN", name: "Amgen", sector: "Health Care", tier: "mega" },
  { ticker: "AMP", name: "Ameriprise Financial", sector: "Financials", tier: "large" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate", tier: "large" },
  { ticker: "AMZN", name: "Amazon", sector: "Consumer Discretionary", tier: "mega" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology", tier: "mega" },
  { ticker: "AON", name: "Aon plc", sector: "Financials", tier: "large" },
  { ticker: "AOS", name: "A. O. Smith", sector: "Industrials", tier: "mid" },
  { ticker: "APA", name: "APA Corporation", sector: "Energy", tier: "mid" },
  { ticker: "APD", name: "Air Products", sector: "Materials", tier: "large" },
  { ticker: "APH", name: "Amphenol", sector: "Technology", tier: "mega" },
  { ticker: "APO", name: "Apollo Global Management", sector: "Financials", tier: "large" },
  { ticker: "APP", name: "AppLovin", sector: "Communication Services", tier: "large" },
  { ticker: "APTV", name: "Aptiv", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities", sector: "Real Estate", tier: "mid" },
  { ticker: "ARES", name: "Ares Management", sector: "Financials", tier: "large" },
  { ticker: "ATO", name: "Atmos Energy", sector: "Utilities", tier: "large" },
  { ticker: "AVGO", name: "Broadcom", sector: "Technology", tier: "mega" },
  { ticker: "AVY", name: "Avery Dennison", sector: "Materials", tier: "mid" },
  { ticker: "AWK", name: "American Water Works", sector: "Utilities", tier: "large" },
  { ticker: "AXON", name: "Axon Enterprise", sector: "Industrials", tier: "large" },
  { ticker: "AXP", name: "American Express", sector: "Financials", tier: "mega" },
  { ticker: "AZO", name: "AutoZone", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "BA", name: "Boeing", sector: "Industrials", tier: "large" },
  { ticker: "BAC", name: "Bank of America", sector: "Financials", tier: "mega" },
  { ticker: "BALL", name: "Ball Corporation", sector: "Materials", tier: "large" },
  { ticker: "BAX", name: "Baxter International", sector: "Health Care", tier: "mid" },
  { ticker: "BBY", name: "Best Buy", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "BDX", name: "Becton Dickinson", sector: "Health Care", tier: "large" },
  { ticker: "BEN", name: "Franklin Resources", sector: "Financials", tier: "large" },
  { ticker: "BF.B", name: "Brown–Forman", sector: "Consumer Staples", tier: "mid" },
  { ticker: "BG", name: "Bunge Global", sector: "Consumer Staples", tier: "large" },
  { ticker: "BIIB", name: "Biogen", sector: "Health Care", tier: "large" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy", tier: "large" },
  { ticker: "BLDR", name: "Builders FirstSource", sector: "Industrials", tier: "mid" },
  { ticker: "BLK", name: "BlackRock", sector: "Financials", tier: "large" },
  { ticker: "BMY", name: "Bristol Myers Squibb", sector: "Health Care", tier: "large" },
  { ticker: "BNY", name: "BNY Mellon", sector: "Financials", tier: "large" },
  { ticker: "BR", name: "Broadridge Financial Solutions", sector: "Industrials", tier: "large" },
  { ticker: "BRK.B", name: "Berkshire Hathaway", sector: "Financials", tier: "mega" },
  { ticker: "BRO", name: "Brown & Brown", sector: "Financials", tier: "large" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Health Care", tier: "large" },
  { ticker: "BX", name: "Blackstone Inc.", sector: "Financials", tier: "large" },
  { ticker: "BXP", name: "BXP, Inc.", sector: "Real Estate", tier: "mid" },
  { ticker: "C", name: "Citigroup", sector: "Financials", tier: "mega" },
  { ticker: "CAH", name: "Cardinal Health", sector: "Health Care", tier: "large" },
  { ticker: "CARR", name: "Carrier Global", sector: "Industrials", tier: "large" },
  { ticker: "CASY", name: "Casey's", sector: "Consumer Staples", tier: "large" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", tier: "mega" },
  { ticker: "CB", name: "Chubb Limited", sector: "Financials", tier: "large" },
  { ticker: "CBOE", name: "Cboe Global Markets", sector: "Financials", tier: "large" },
  { ticker: "CBRE", name: "CBRE Group", sector: "Real Estate", tier: "large" },
  { ticker: "CCI", name: "Crown Castle", sector: "Real Estate", tier: "large" },
  { ticker: "CCL", name: "Carnival Corporation", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "CDNS", name: "Cadence Design Systems", sector: "Technology", tier: "large" },
  { ticker: "CDW", name: "CDW Corporation", sector: "Technology", tier: "large" },
  { ticker: "CEG", name: "Constellation Energy", sector: "Utilities", tier: "large" },
  { ticker: "CF", name: "CF Industries", sector: "Materials", tier: "large" },
  { ticker: "CFG", name: "Citizens Financial Group", sector: "Financials", tier: "large" },
  { ticker: "CHD", name: "Church & Dwight", sector: "Consumer Staples", tier: "large" },
  { ticker: "CHRW", name: "C.H. Robinson", sector: "Industrials", tier: "large" },
  { ticker: "CHTR", name: "Charter Communications", sector: "Communication Services", tier: "large" },
  { ticker: "CI", name: "Cigna", sector: "Health Care", tier: "large" },
  { ticker: "CIEN", name: "Ciena", sector: "Technology", tier: "large" },
  { ticker: "CINF", name: "Cincinnati Financial", sector: "Financials", tier: "large" },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Staples", tier: "large" },
  { ticker: "CLX", name: "Clorox", sector: "Consumer Staples", tier: "mid" },
  { ticker: "CMCSA", name: "Comcast", sector: "Communication Services", tier: "large" },
  { ticker: "CME", name: "CME Group", sector: "Financials", tier: "large" },
  { ticker: "CMG", name: "Chipotle Mexican Grill", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "CMI", name: "Cummins", sector: "Industrials", tier: "large" },
  { ticker: "CMS", name: "CMS Energy", sector: "Utilities", tier: "large" },
  { ticker: "CNC", name: "Centene Corporation", sector: "Health Care", tier: "large" },
  { ticker: "CNP", name: "CenterPoint Energy", sector: "Utilities", tier: "large" },
  { ticker: "COF", name: "Capital One", sector: "Financials", tier: "large" },
  { ticker: "COHR", name: "Coherent Corp.", sector: "Technology", tier: "large" },
  { ticker: "COIN", name: "Coinbase", sector: "Financials", tier: "large" },
  { ticker: "COO", name: "Cooper Companies (The)", sector: "Health Care", tier: "mid" },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy", tier: "large" },
  { ticker: "COR", name: "Cencora", sector: "Health Care", tier: "large" },
  { ticker: "COST", name: "Costco", sector: "Consumer Staples", tier: "mega" },
  { ticker: "CPAY", name: "Corpay", sector: "Financials", tier: "large" },
  { ticker: "CPRT", name: "Copart", sector: "Industrials", tier: "large" },
  { ticker: "CPT", name: "Camden Property Trust", sector: "Real Estate", tier: "mid" },
  { ticker: "CRH", name: "CRH plc", sector: "Materials", tier: "large" },
  { ticker: "CRL", name: "Charles River Laboratories", sector: "Health Care", tier: "mid" },
  { ticker: "CRM", name: "Salesforce", sector: "Technology", tier: "mega" },
  { ticker: "CRWD", name: "CrowdStrike", sector: "Technology", tier: "mega" },
  { ticker: "CSCO", name: "Cisco", sector: "Technology", tier: "mega" },
  { ticker: "CSGP", name: "CoStar Group", sector: "Real Estate", tier: "mid" },
  { ticker: "CSX", name: "CSX Corporation", sector: "Industrials", tier: "large" },
  { ticker: "CTAS", name: "Cintas", sector: "Industrials", tier: "large" },
  { ticker: "CTSH", name: "Cognizant", sector: "Technology", tier: "large" },
  { ticker: "CTVA", name: "Corteva", sector: "Materials", tier: "large" },
  { ticker: "CVNA", name: "Carvana", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "CVS", name: "CVS Health", sector: "Health Care", tier: "large" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy", tier: "mega" },
  { ticker: "D", name: "Dominion Energy", sector: "Utilities", tier: "large" },
  { ticker: "DAL", name: "Delta Air Lines", sector: "Industrials", tier: "large" },
  { ticker: "DASH", name: "DoorDash", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "DD", name: "DuPont", sector: "Industrials", tier: "large" },
  { ticker: "DDOG", name: "Datadog", sector: "Technology", tier: "large" },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", tier: "large" },
  { ticker: "DECK", name: "Deckers Brands", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "DELL", name: "Dell Technologies", sector: "Technology", tier: "mega" },
  { ticker: "DG", name: "Dollar General", sector: "Consumer Staples", tier: "large" },
  { ticker: "DGX", name: "Quest Diagnostics", sector: "Health Care", tier: "large" },
  { ticker: "DHI", name: "D. R. Horton", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Health Care", tier: "large" },
  { ticker: "DIS", name: "Walt Disney Company (The)", sector: "Communication Services", tier: "large" },
  { ticker: "DLR", name: "Digital Realty", sector: "Real Estate", tier: "large" },
  { ticker: "DLTR", name: "Dollar Tree", sector: "Consumer Staples", tier: "large" },
  { ticker: "DOC", name: "Healthpeak Properties", sector: "Real Estate", tier: "mid" },
  { ticker: "DOV", name: "Dover Corporation", sector: "Industrials", tier: "large" },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials", tier: "large" },
  { ticker: "DPZ", name: "Domino's", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "DRI", name: "Darden Restaurants", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "DTE", name: "DTE Energy", sector: "Utilities", tier: "large" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities", tier: "large" },
  { ticker: "DVA", name: "DaVita", sector: "Health Care", tier: "mid" },
  { ticker: "DVN", name: "Devon Energy", sector: "Energy", tier: "large" },
  { ticker: "DXCM", name: "Dexcom", sector: "Health Care", tier: "large" },
  { ticker: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "ECHO", name: "EchoStar", sector: "Communication Services", tier: "large" },
  { ticker: "ECL", name: "Ecolab", sector: "Materials", tier: "large" },
  { ticker: "ED", name: "Consolidated Edison", sector: "Utilities", tier: "large" },
  { ticker: "EFX", name: "Equifax", sector: "Industrials", tier: "large" },
  { ticker: "EG", name: "Everest Group", sector: "Financials", tier: "mid" },
  { ticker: "EIX", name: "Edison International", sector: "Utilities", tier: "large" },
  { ticker: "EL", name: "Estée Lauder Companies (The)", sector: "Consumer Staples", tier: "large" },
  { ticker: "ELV", name: "Elevance Health", sector: "Health Care", tier: "large" },
  { ticker: "EME", name: "Emcor", sector: "Industrials", tier: "large" },
  { ticker: "EMR", name: "Emerson Electric", sector: "Industrials", tier: "large" },
  { ticker: "EOG", name: "EOG Resources", sector: "Energy", tier: "large" },
  { ticker: "EQIX", name: "Equinix", sector: "Real Estate", tier: "large" },
  { ticker: "EQT", name: "EQT Corporation", sector: "Energy", tier: "large" },
  { ticker: "ERIE", name: "Erie Indemnity", sector: "Financials", tier: "mid" },
  { ticker: "ES", name: "Eversource Energy", sector: "Utilities", tier: "large" },
  { ticker: "ESS", name: "Essex Property Trust", sector: "Real Estate", tier: "large" },
  { ticker: "ETN", name: "Eaton Corporation", sector: "Industrials", tier: "large" },
  { ticker: "ETR", name: "Entergy", sector: "Utilities", tier: "large" },
  { ticker: "EVRG", name: "Evergy", sector: "Utilities", tier: "large" },
  { ticker: "EW", name: "Edwards Lifesciences", sector: "Health Care", tier: "large" },
  { ticker: "EXC", name: "Exelon", sector: "Utilities", tier: "large" },
  { ticker: "EXE", name: "Expand Energy", sector: "Energy", tier: "large" },
  { ticker: "EXPD", name: "Expeditors International", sector: "Industrials", tier: "large" },
  { ticker: "EXPE", name: "Expedia Group", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "EXR", name: "Extra Space Storage", sector: "Real Estate", tier: "large" },
  { ticker: "F", name: "Ford Motor Company", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "FANG", name: "Diamondback Energy", sector: "Energy", tier: "large" },
  { ticker: "FAST", name: "Fastenal", sector: "Industrials", tier: "large" },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", tier: "large" },
  { ticker: "FDS", name: "FactSet", sector: "Financials", tier: "mid" },
  { ticker: "FDX", name: "FedEx", sector: "Industrials", tier: "large" },
  { ticker: "FDXF", name: "FedEx Freight", sector: "Industrials", tier: "large" },
  { ticker: "FE", name: "FirstEnergy", sector: "Utilities", tier: "large" },
  { ticker: "FERG", name: "Ferguson Enterprises", sector: "Industrials", tier: "large" },
  { ticker: "FFIV", name: "F5, Inc.", sector: "Technology", tier: "large" },
  { ticker: "FICO", name: "Fair Isaac", sector: "Technology", tier: "large" },
  { ticker: "FIS", name: "Fidelity National Information Services", sector: "Financials", tier: "large" },
  { ticker: "FISV", name: "Fiserv", sector: "Financials", tier: "large" },
  { ticker: "FITB", name: "Fifth Third Bancorp", sector: "Financials", tier: "large" },
  { ticker: "FIX", name: "Comfort Systems USA", sector: "Industrials", tier: "large" },
  { ticker: "FLEX", name: "Flex Ltd.", sector: "Technology", tier: "large" },
  { ticker: "FOX", name: "Fox Corporation (Class B)", sector: "Communication Services", tier: "large" },
  { ticker: "FOXA", name: "Fox Corporation (Class A)", sector: "Communication Services", tier: "large" },
  { ticker: "FRT", name: "Federal Realty Investment Trust", sector: "Real Estate", tier: "mid" },
  { ticker: "FSLR", name: "First Solar", sector: "Technology", tier: "large" },
  { ticker: "FTNT", name: "Fortinet", sector: "Technology", tier: "large" },
  { ticker: "FTV", name: "Fortive", sector: "Industrials", tier: "large" },
  { ticker: "GD", name: "General Dynamics", sector: "Industrials", tier: "large" },
  { ticker: "GDDY", name: "GoDaddy", sector: "Technology", tier: "mid" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials", tier: "mega" },
  { ticker: "GEHC", name: "GE HealthCare", sector: "Health Care", tier: "large" },
  { ticker: "GEN", name: "Gen Digital", sector: "Technology", tier: "large" },
  { ticker: "GEV", name: "GE Vernova", sector: "Industrials", tier: "mega" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Health Care", tier: "large" },
  { ticker: "GIS", name: "General Mills", sector: "Consumer Staples", tier: "large" },
  { ticker: "GL", name: "Globe Life", sector: "Financials", tier: "mid" },
  { ticker: "GLW", name: "Corning Inc.", sector: "Technology", tier: "large" },
  { ticker: "GM", name: "General Motors", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "GNRC", name: "Generac", sector: "Industrials", tier: "mid" },
  { ticker: "GOOG", name: "Alphabet Inc. (Class C)", sector: "Communication Services", tier: "mega" },
  { ticker: "GOOGL", name: "Alphabet Inc. (Class A)", sector: "Communication Services", tier: "mega" },
  { ticker: "GPC", name: "Genuine Parts Company", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "GPN", name: "Global Payments", sector: "Financials", tier: "large" },
  { ticker: "GRMN", name: "Garmin", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financials", tier: "mega" },
  { ticker: "GWW", name: "W. W. Grainger", sector: "Industrials", tier: "large" },
  { ticker: "HAL", name: "Halliburton", sector: "Energy", tier: "large" },
  { ticker: "HAS", name: "Hasbro", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "HBAN", name: "Huntington Bancshares", sector: "Financials", tier: "large" },
  { ticker: "HCA", name: "HCA Healthcare", sector: "Health Care", tier: "large" },
  { ticker: "HD", name: "Home Depot (The)", sector: "Consumer Discretionary", tier: "mega" },
  { ticker: "HIG", name: "Hartford (The)", sector: "Financials", tier: "large" },
  { ticker: "HII", name: "Huntington Ingalls Industries", sector: "Industrials", tier: "mid" },
  { ticker: "HLT", name: "Hilton Worldwide", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "HON", name: "Honeywell Technologies", sector: "Industrials", tier: "large" },
  { ticker: "HONA", name: "Honeywell Aerospace", sector: "Industrials", tier: "large" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Financials", tier: "large" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology", tier: "large" },
  { ticker: "HPQ", name: "HP Inc.", sector: "Technology", tier: "large" },
  { ticker: "HRL", name: "Hormel Foods", sector: "Consumer Staples", tier: "mid" },
  { ticker: "HSIC", name: "Henry Schein", sector: "Health Care", tier: "mid" },
  { ticker: "HST", name: "Host Hotels & Resorts", sector: "Real Estate", tier: "large" },
  { ticker: "HSY", name: "Hershey Company (The)", sector: "Consumer Staples", tier: "large" },
  { ticker: "HUBB", name: "Hubbell Incorporated", sector: "Industrials", tier: "large" },
  { ticker: "HUM", name: "Humana", sector: "Health Care", tier: "large" },
  { ticker: "HWM", name: "Howmet Aerospace", sector: "Industrials", tier: "large" },
  { ticker: "IBKR", name: "Interactive Brokers", sector: "Financials", tier: "large" },
  { ticker: "IBM", name: "IBM", sector: "Technology", tier: "mega" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Financials", tier: "large" },
  { ticker: "IDXX", name: "Idexx Laboratories", sector: "Health Care", tier: "large" },
  { ticker: "IEX", name: "IDEX Corporation", sector: "Industrials", tier: "large" },
  { ticker: "IFF", name: "International Flavors & Fragrances", sector: "Materials", tier: "large" },
  { ticker: "INCY", name: "Incyte", sector: "Health Care", tier: "large" },
  { ticker: "INTC", name: "Intel", sector: "Technology", tier: "mega" },
  { ticker: "INTU", name: "Intuit", sector: "Technology", tier: "large" },
  { ticker: "INVH", name: "Invitation Homes", sector: "Real Estate", tier: "large" },
  { ticker: "IP", name: "International Paper", sector: "Materials", tier: "large" },
  { ticker: "IQV", name: "IQVIA", sector: "Health Care", tier: "large" },
  { ticker: "IR", name: "Ingersoll Rand", sector: "Industrials", tier: "large" },
  { ticker: "IRM", name: "Iron Mountain", sector: "Real Estate", tier: "large" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Health Care", tier: "large" },
  { ticker: "IT", name: "Gartner", sector: "Technology", tier: "mid" },
  { ticker: "ITW", name: "Illinois Tool Works", sector: "Industrials", tier: "large" },
  { ticker: "IVZ", name: "Invesco", sector: "Financials", tier: "mid" },
  { ticker: "J", name: "Jacobs Solutions", sector: "Industrials", tier: "large" },
  { ticker: "JBHT", name: "J.B. Hunt", sector: "Industrials", tier: "large" },
  { ticker: "JBL", name: "Jabil", sector: "Technology", tier: "large" },
  { ticker: "JCI", name: "Johnson Controls", sector: "Industrials", tier: "large" },
  { ticker: "JKHY", name: "Jack Henry & Associates", sector: "Financials", tier: "mid" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Health Care", tier: "mega" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials", tier: "mega" },
  { ticker: "KDP", name: "Keurig Dr Pepper", sector: "Consumer Staples", tier: "large" },
  { ticker: "KEY", name: "KeyCorp", sector: "Financials", tier: "large" },
  { ticker: "KEYS", name: "Keysight Technologies", sector: "Technology", tier: "large" },
  { ticker: "KHC", name: "Kraft Heinz", sector: "Consumer Staples", tier: "large" },
  { ticker: "KIM", name: "Kimco Realty", sector: "Real Estate", tier: "large" },
  { ticker: "KKR", name: "KKR & Co.", sector: "Financials", tier: "large" },
  { ticker: "KLAC", name: "KLA Corporation", sector: "Technology", tier: "mega" },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer Staples", tier: "large" },
  { ticker: "KMI", name: "Kinder Morgan", sector: "Energy", tier: "large" },
  { ticker: "KO", name: "Coca-Cola Company (The)", sector: "Consumer Staples", tier: "mega" },
  { ticker: "KR", name: "Kroger", sector: "Consumer Staples", tier: "large" },
  { ticker: "KVUE", name: "Kenvue", sector: "Consumer Staples", tier: "large" },
  { ticker: "L", name: "Loews Corporation", sector: "Financials", tier: "large" },
  { ticker: "LDOS", name: "Leidos", sector: "Industrials", tier: "large" },
  { ticker: "LEN", name: "Lennar", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "LH", name: "Labcorp", sector: "Health Care", tier: "large" },
  { ticker: "LHX", name: "L3Harris", sector: "Industrials", tier: "large" },
  { ticker: "LII", name: "Lennox International", sector: "Industrials", tier: "mid" },
  { ticker: "LIN", name: "Linde plc", sector: "Materials", tier: "mega" },
  { ticker: "LITE", name: "Lumentum", sector: "Technology", tier: "large" },
  { ticker: "LLY", name: "Lilly (Eli)", sector: "Health Care", tier: "mega" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", tier: "large" },
  { ticker: "LNT", name: "Alliant Energy", sector: "Utilities", tier: "large" },
  { ticker: "LOW", name: "Lowe's", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", tier: "mega" },
  { ticker: "LULU", name: "Lululemon Athletica", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "LUV", name: "Southwest Airlines", sector: "Industrials", tier: "large" },
  { ticker: "LVS", name: "Las Vegas Sands", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "LYB", name: "LyondellBasell", sector: "Materials", tier: "large" },
  { ticker: "LYV", name: "Live Nation Entertainment", sector: "Communication Services", tier: "large" },
  { ticker: "MA", name: "Mastercard", sector: "Financials", tier: "mega" },
  { ticker: "MAA", name: "Mid-America Apartment Communities", sector: "Real Estate", tier: "large" },
  { ticker: "MAR", name: "Marriott International", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "MAS", name: "Masco", sector: "Industrials", tier: "mid" },
  { ticker: "MCD", name: "McDonald's", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "MCHP", name: "Microchip Technology", sector: "Technology", tier: "large" },
  { ticker: "MCK", name: "McKesson Corporation", sector: "Health Care", tier: "large" },
  { ticker: "MCO", name: "Moody's Corporation", sector: "Financials", tier: "large" },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Staples", tier: "large" },
  { ticker: "MDT", name: "Medtronic", sector: "Health Care", tier: "large" },
  { ticker: "MET", name: "MetLife", sector: "Financials", tier: "large" },
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services", tier: "mega" },
  { ticker: "MGM", name: "MGM Resorts", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "MKC", name: "McCormick & Company", sector: "Consumer Staples", tier: "mid" },
  { ticker: "MLM", name: "Martin Marietta Materials", sector: "Materials", tier: "large" },
  { ticker: "MMM", name: "3M", sector: "Industrials", tier: "large" },
  { ticker: "MNST", name: "Monster Beverage", sector: "Consumer Staples", tier: "large" },
  { ticker: "MO", name: "Altria", sector: "Consumer Staples", tier: "large" },
  { ticker: "MOS", name: "Mosaic Company (The)", sector: "Materials", tier: "mid" },
  { ticker: "MPC", name: "Marathon Petroleum", sector: "Energy", tier: "large" },
  { ticker: "MPWR", name: "Monolithic Power Systems", sector: "Technology", tier: "large" },
  { ticker: "MRK", name: "Merck & Co.", sector: "Health Care", tier: "mega" },
  { ticker: "MRNA", name: "Moderna", sector: "Health Care", tier: "large" },
  { ticker: "MRSH", name: "Marsh McLennan", sector: "Financials", tier: "large" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", tier: "large" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials", tier: "mega" },
  { ticker: "MSCI", name: "MSCI", sector: "Financials", tier: "large" },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology", tier: "mega" },
  { ticker: "MSI", name: "Motorola Solutions", sector: "Technology", tier: "large" },
  { ticker: "MTB", name: "M&T Bank", sector: "Financials", tier: "large" },
  { ticker: "MTD", name: "Mettler Toledo", sector: "Health Care", tier: "large" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology", tier: "mega" },
  { ticker: "NCLH", name: "Norwegian Cruise Line Holdings", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "NDAQ", name: "Nasdaq, Inc.", sector: "Financials", tier: "large" },
  { ticker: "NDSN", name: "Nordson Corporation", sector: "Industrials", tier: "large" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities", tier: "large" },
  { ticker: "NEM", name: "Newmont", sector: "Materials", tier: "large" },
  { ticker: "NFLX", name: "Netflix", sector: "Communication Services", tier: "mega" },
  { ticker: "NI", name: "NiSource", sector: "Utilities", tier: "large" },
  { ticker: "NKE", name: "Nike, Inc.", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Industrials", tier: "large" },
  { ticker: "NOW", name: "ServiceNow", sector: "Technology", tier: "large" },
  { ticker: "NRG", name: "NRG Energy", sector: "Utilities", tier: "large" },
  { ticker: "NSC", name: "Norfolk Southern", sector: "Industrials", tier: "large" },
  { ticker: "NTAP", name: "NetApp", sector: "Technology", tier: "large" },
  { ticker: "NTRS", name: "Northern Trust", sector: "Financials", tier: "large" },
  { ticker: "NUE", name: "Nucor", sector: "Materials", tier: "large" },
  { ticker: "NVDA", name: "Nvidia", sector: "Technology", tier: "mega" },
  { ticker: "NVR", name: "NVR, Inc.", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "NWS", name: "News Corp (Class B)", sector: "Communication Services", tier: "large" },
  { ticker: "NWSA", name: "News Corp (Class A)", sector: "Communication Services", tier: "large" },
  { ticker: "NXPI", name: "NXP Semiconductors", sector: "Technology", tier: "large" },
  { ticker: "O", name: "Realty Income", sector: "Real Estate", tier: "large" },
  { ticker: "ODFL", name: "Old Dominion", sector: "Industrials", tier: "large" },
  { ticker: "OKE", name: "Oneok", sector: "Energy", tier: "large" },
  { ticker: "OMC", name: "Omnicom Group", sector: "Communication Services", tier: "large" },
  { ticker: "ON", name: "ON Semiconductor", sector: "Technology", tier: "large" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology", tier: "mega" },
  { ticker: "ORLY", name: "O'Reilly Automotive", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "OTIS", name: "Otis Worldwide", sector: "Industrials", tier: "large" },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", tier: "large" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", tier: "mega" },
  { ticker: "PAYX", name: "Paychex", sector: "Industrials", tier: "large" },
  { ticker: "PCAR", name: "Paccar", sector: "Industrials", tier: "large" },
  { ticker: "PCG", name: "PG&E Corporation", sector: "Utilities", tier: "large" },
  { ticker: "PEG", name: "Public Service Enterprise Group", sector: "Utilities", tier: "large" },
  { ticker: "PEP", name: "PepsiCo", sector: "Consumer Staples", tier: "large" },
  { ticker: "PFE", name: "Pfizer", sector: "Health Care", tier: "large" },
  { ticker: "PFG", name: "Principal Financial Group", sector: "Financials", tier: "large" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples", tier: "mega" },
  { ticker: "PGR", name: "Progressive Corporation", sector: "Financials", tier: "large" },
  { ticker: "PH", name: "Parker Hannifin", sector: "Industrials", tier: "large" },
  { ticker: "PHM", name: "PulteGroup", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "PKG", name: "Packaging Corporation of America", sector: "Materials", tier: "large" },
  { ticker: "PLD", name: "Prologis", sector: "Real Estate", tier: "large" },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", tier: "mega" },
  { ticker: "PM", name: "Philip Morris International", sector: "Consumer Staples", tier: "mega" },
  { ticker: "PNC", name: "PNC Financial Services", sector: "Financials", tier: "large" },
  { ticker: "PNR", name: "Pentair", sector: "Industrials", tier: "mid" },
  { ticker: "PNW", name: "Pinnacle West Capital", sector: "Utilities", tier: "mid" },
  { ticker: "PODD", name: "Insulet Corporation", sector: "Health Care", tier: "mid" },
  { ticker: "PPG", name: "PPG Industries", sector: "Materials", tier: "large" },
  { ticker: "PPL", name: "PPL Corporation", sector: "Utilities", tier: "large" },
  { ticker: "PRU", name: "Prudential Financial", sector: "Financials", tier: "large" },
  { ticker: "PSA", name: "Public Storage", sector: "Real Estate", tier: "large" },
  { ticker: "PSKY", name: "Paramount Skydance Corporation", sector: "Communication Services", tier: "mid" },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", tier: "large" },
  { ticker: "PTC", name: "PTC Inc.", sector: "Technology", tier: "large" },
  { ticker: "PWR", name: "Quanta Services", sector: "Industrials", tier: "large" },
  { ticker: "PYPL", name: "PayPal", sector: "Financials", tier: "large" },
  { ticker: "Q", name: "Qnity Electronics", sector: "Technology", tier: "large" },
  { ticker: "QCOM", name: "Qualcomm", sector: "Technology", tier: "large" },
  { ticker: "RCL", name: "Royal Caribbean Group", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "RDDT", name: "Reddit", sector: "Communication Services", tier: "large" },
  { ticker: "REG", name: "Regency Centers", sector: "Real Estate", tier: "mid" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals", sector: "Health Care", tier: "large" },
  { ticker: "RF", name: "Regions Financial Corporation", sector: "Financials", tier: "large" },
  { ticker: "RJF", name: "Raymond James Financial", sector: "Financials", tier: "large" },
  { ticker: "RL", name: "Ralph Lauren Corporation", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "RMD", name: "ResMed", sector: "Health Care", tier: "large" },
  { ticker: "ROK", name: "Rockwell Automation", sector: "Industrials", tier: "large" },
  { ticker: "ROL", name: "Rollins, Inc.", sector: "Industrials", tier: "large" },
  { ticker: "ROP", name: "Roper Technologies", sector: "Technology", tier: "large" },
  { ticker: "ROST", name: "Ross Stores", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "RSG", name: "Republic Services", sector: "Industrials", tier: "large" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials", tier: "mega" },
  { ticker: "RVTY", name: "Revvity", sector: "Health Care", tier: "mid" },
  { ticker: "SBAC", name: "SBA Communications", sector: "Real Estate", tier: "large" },
  { ticker: "SBUX", name: "Starbucks", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "SCHW", name: "Charles Schwab Corporation", sector: "Financials", tier: "large" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials", tier: "large" },
  { ticker: "SJM", name: "J.M. Smucker Company (The)", sector: "Consumer Staples", tier: "mid" },
  { ticker: "SLB", name: "Schlumberger", sector: "Energy", tier: "large" },
  { ticker: "SMCI", name: "Supermicro", sector: "Technology", tier: "large" },
  { ticker: "SNA", name: "Snap-on", sector: "Industrials", tier: "large" },
  { ticker: "SNDK", name: "Sandisk", sector: "Technology", tier: "mega" },
  { ticker: "SNPS", name: "Synopsys", sector: "Technology", tier: "large" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities", tier: "large" },
  { ticker: "SOLV", name: "Solventum", sector: "Health Care", tier: "large" },
  { ticker: "SPG", name: "Simon Property Group", sector: "Real Estate", tier: "large" },
  { ticker: "SPGI", name: "S&P Global", sector: "Financials", tier: "large" },
  { ticker: "SRE", name: "Sempra", sector: "Utilities", tier: "large" },
  { ticker: "STE", name: "Steris", sector: "Health Care", tier: "large" },
  { ticker: "STLD", name: "Steel Dynamics", sector: "Materials", tier: "large" },
  { ticker: "STT", name: "State Street Corporation", sector: "Financials", tier: "large" },
  { ticker: "STX", name: "Seagate Technology", sector: "Technology", tier: "large" },
  { ticker: "STZ", name: "Constellation Brands", sector: "Consumer Staples", tier: "large" },
  { ticker: "SW", name: "Smurfit Westrock", sector: "Materials", tier: "large" },
  { ticker: "SWK", name: "Stanley Black & Decker", sector: "Industrials", tier: "mid" },
  { ticker: "SWKS", name: "Skyworks Solutions", sector: "Technology", tier: "mid" },
  { ticker: "SYF", name: "Synchrony Financial", sector: "Financials", tier: "large" },
  { ticker: "SYK", name: "Stryker Corporation", sector: "Health Care", tier: "large" },
  { ticker: "SYY", name: "Sysco", sector: "Consumer Staples", tier: "large" },
  { ticker: "T", name: "AT&T", sector: "Communication Services", tier: "large" },
  { ticker: "TAP", name: "Molson Coors Beverage Company", sector: "Consumer Staples", tier: "mid" },
  { ticker: "TDG", name: "TransDigm Group", sector: "Industrials", tier: "large" },
  { ticker: "TDY", name: "Teledyne Technologies", sector: "Technology", tier: "large" },
  { ticker: "TECH", name: "Bio-Techne", sector: "Health Care", tier: "mid" },
  { ticker: "TEL", name: "TE Connectivity", sector: "Technology", tier: "large" },
  { ticker: "TER", name: "Teradyne", sector: "Technology", tier: "large" },
  { ticker: "TFC", name: "Truist Financial", sector: "Financials", tier: "large" },
  { ticker: "TGT", name: "Target Corporation", sector: "Consumer Staples", tier: "large" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "TKO", name: "TKO Group Holdings", sector: "Communication Services", tier: "large" },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Health Care", tier: "mega" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication Services", tier: "large" },
  { ticker: "TPL", name: "Texas Pacific Land Corporation", sector: "Energy", tier: "large" },
  { ticker: "TPR", name: "Tapestry, Inc.", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "TRGP", name: "Targa Resources", sector: "Energy", tier: "large" },
  { ticker: "TRMB", name: "Trimble Inc.", sector: "Technology", tier: "mid" },
  { ticker: "TROW", name: "T. Rowe Price", sector: "Financials", tier: "large" },
  { ticker: "TRV", name: "Travelers Companies (The)", sector: "Financials", tier: "large" },
  { ticker: "TSCO", name: "Tractor Supply", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "TSLA", name: "Tesla, Inc.", sector: "Consumer Discretionary", tier: "mega" },
  { ticker: "TSN", name: "Tyson Foods", sector: "Consumer Staples", tier: "large" },
  { ticker: "TT", name: "Trane Technologies", sector: "Industrials", tier: "large" },
  { ticker: "TTD", name: "Trade Desk (The)", sector: "Communication Services", tier: "mid" },
  { ticker: "TTWO", name: "Take-Two Interactive", sector: "Communication Services", tier: "large" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", tier: "mega" },
  { ticker: "TXT", name: "Textron", sector: "Industrials", tier: "mid" },
  { ticker: "TYL", name: "Tyler Technologies", sector: "Technology", tier: "mid" },
  { ticker: "UAL", name: "United Airlines Holdings", sector: "Industrials", tier: "large" },
  { ticker: "UBER", name: "Uber", sector: "Industrials", tier: "large" },
  { ticker: "UDR", name: "UDR, Inc.", sector: "Real Estate", tier: "mid" },
  { ticker: "UHS", name: "Universal Health Services", sector: "Health Care", tier: "mid" },
  { ticker: "ULTA", name: "Ulta Beauty", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Health Care", tier: "mega" },
  { ticker: "UNP", name: "Union Pacific Corporation", sector: "Industrials", tier: "large" },
  { ticker: "UPS", name: "United Parcel Service", sector: "Industrials", tier: "large" },
  { ticker: "URI", name: "United Rentals", sector: "Industrials", tier: "large" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials", tier: "large" },
  { ticker: "V", name: "Visa Inc.", sector: "Financials", tier: "mega" },
  { ticker: "VEEV", name: "Veeva Systems", sector: "Health Care", tier: "large" },
  { ticker: "VICI", name: "Vici Properties", sector: "Real Estate", tier: "large" },
  { ticker: "VLO", name: "Valero Energy", sector: "Energy", tier: "large" },
  { ticker: "VLTO", name: "Veralto", sector: "Industrials", tier: "large" },
  { ticker: "VMC", name: "Vulcan Materials Company", sector: "Materials", tier: "large" },
  { ticker: "VMRK", name: "Vivmark Residential (formerly Equity Residential)", sector: "Real Estate", tier: "large" },
  { ticker: "VRSK", name: "Verisk Analytics", sector: "Industrials", tier: "large" },
  { ticker: "VRSN", name: "Verisign", sector: "Technology", tier: "large" },
  { ticker: "VRT", name: "Vertiv", sector: "Industrials", tier: "large" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Health Care", tier: "large" },
  { ticker: "VST", name: "Vistra Corp.", sector: "Utilities", tier: "large" },
  { ticker: "VTR", name: "Ventas", sector: "Real Estate", tier: "large" },
  { ticker: "VTRS", name: "Viatris", sector: "Health Care", tier: "large" },
  { ticker: "VZ", name: "Verizon", sector: "Communication Services", tier: "mega" },
  { ticker: "WAB", name: "Wabtec", sector: "Industrials", tier: "large" },
  { ticker: "WAT", name: "Waters Corporation", sector: "Health Care", tier: "large" },
  { ticker: "WBD", name: "Warner Bros. Discovery", sector: "Communication Services", tier: "large" },
  { ticker: "WDAY", name: "Workday, Inc.", sector: "Technology", tier: "large" },
  { ticker: "WDC", name: "Western Digital", sector: "Technology", tier: "large" },
  { ticker: "WEC", name: "WEC Energy Group", sector: "Utilities", tier: "large" },
  { ticker: "WELL", name: "Welltower", sector: "Real Estate", tier: "large" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financials", tier: "mega" },
  { ticker: "WM", name: "Waste Management", sector: "Industrials", tier: "large" },
  { ticker: "WMB", name: "Williams Companies", sector: "Energy", tier: "large" },
  { ticker: "WMT", name: "Walmart", sector: "Consumer Staples", tier: "mega" },
  { ticker: "WRB", name: "W. R. Berkley Corporation", sector: "Financials", tier: "large" },
  { ticker: "WSM", name: "Williams-Sonoma, Inc.", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "WST", name: "West Pharmaceutical Services", sector: "Health Care", tier: "large" },
  { ticker: "WTW", name: "Willis Towers Watson", sector: "Financials", tier: "large" },
  { ticker: "WY", name: "Weyerhaeuser", sector: "Real Estate", tier: "large" },
  { ticker: "WYNN", name: "Wynn Resorts", sector: "Consumer Discretionary", tier: "mid" },
  { ticker: "XEL", name: "Xcel Energy", sector: "Utilities", tier: "large" },
  { ticker: "XOM", name: "ExxonMobil", sector: "Energy", tier: "mega" },
  { ticker: "XYL", name: "Xylem Inc.", sector: "Industrials", tier: "large" },
  { ticker: "XYZ", name: "Block, Inc.", sector: "Financials", tier: "large" },
  { ticker: "YUM", name: "Yum! Brands", sector: "Consumer Discretionary", tier: "large" },
  { ticker: "ZBH", name: "Zimmer Biomet", sector: "Health Care", tier: "large" },
  { ticker: "ZBRA", name: "Zebra Technologies", sector: "Technology", tier: "large" },
  { ticker: "ZTS", name: "Zoetis", sector: "Health Care", tier: "large" },
];
