import {
  AlphaTrendLineDiagram,
  AlphaTrendCrossDiagram,
} from "@/components/diagrams/AlphaTrendDiagrams";
import AnnotatedImage from "@/components/diagrams/AnnotatedImage";

export const meta = {
  slug: "alphatrend-kivancozbilgic",
  name: "AlphaTrend",
  developer: "KivancOzbilgic",
  category: "Trend",
  summary:
    "ATR trailing line filtered by MFI/RSI momentum — ratchets as support in uptrends, resistance in downtrends, with crossover BUY/SELL signals.",
  tradingviewUrl: "https://www.tradingview.com/script/o50NYLAZ-AlphaTrend/",
};

export default function AlphaTrendContent() {
  return (
    <div className="space-y-10">
      <Section title="What it is">
        <p>
          AlphaTrend is a trend/trailing-stop indicator by KivancOzbilgic,
          derived from the older &quot;Trend Magic&quot; script. It&apos;s
          built to do three things at once: mark trend direction, act as a
          moving support/resistance line, and double as an ATR-based trailing
          stop — specifically aimed at reducing how often you get stopped out
          in sideways, choppy conditions.
        </p>
        <p>
          It plots one thick line on price. Internally it also tracks a
          second copy of that line offset by 2 bars, which is what actually
          generates the BUY/SELL signals.
        </p>
      </Section>

      <Section title="How the line is built">
        <p>
          Two trailing candidates are calculated every bar, ATR-distance away
          from price:
        </p>
        <ul className="list-disc list-inside space-y-1 text-parchment-dim font-mono text-xs">
          <li>uptrend candidate = Low − (ATR × Coefficient)</li>
          <li>downtrend candidate = High + (ATR × Coefficient)</li>
        </ul>
        <p>
          Which one is active is decided by a momentum filter — Money Flow
          Index by default (or RSI, if switched on), each read against the 50
          midpoint. When momentum is bullish, the line follows the uptrend
          candidate; when bearish, it follows the downtrend candidate. Within
          each regime the line only moves in its favor — it holds its
          previous value rather than stepping backward — which is what gives
          it the flat, staircase-like look on a chart rather than hugging
          price bar-to-bar.
        </p>
        <AlphaTrendLineDiagram />
      </Section>

      <Section title="Support, resistance, and trailing stop, in one line">
        <p>
          Because of that ratcheting behavior, the same line does three jobs:
          in an uptrend it sits below price as a rising support level (and a
          sensible trailing stop — if price closes back through it, the
          uptrend read is over); in a downtrend it sits above price as
          resistance, doing the mirror job on the short side.
        </p>
      </Section>

      <Section title="BUY / SELL signals">
        <p>
          The signal isn&apos;t generated by watching price cross the line —
          it&apos;s the line crossing its own 2-bar-earlier copy:
        </p>
        <ul className="list-disc list-inside space-y-1 text-parchment-dim">
          <li>
            <strong className="text-gain-bright">BUY</strong> — AlphaTrend
            crosses above its 2-bar offset copy (shaded green on the
            indicator).
          </li>
          <li>
            <strong className="text-loss-bright">SELL</strong> — AlphaTrend
            crosses below its 2-bar offset copy (shaded red).
          </li>
        </ul>
        <p>
          Because it&apos;s comparing the line to a delayed copy of itself
          rather than to price, the signal lags slightly behind the moment
          the underlying trend/momentum actually flips — by design, to avoid
          firing on every minor wiggle.
        </p>
        <AlphaTrendCrossDiagram />
      </Section>

      <Section title="A real chart example">
        <p>
          Below is the publisher&apos;s own example chart from the
          TradingView script page — BTC/USDT, 15-minute, Binance — with
          AlphaTrend plotted and its signal labels visible.
        </p>
        <AnnotatedImage
          src="/indicators/alphatrend-tradingview-example.png"
          alt="AlphaTrend plotted on a BTC/USDT 15-minute chart on TradingView, showing BUY and SELL signal labels"
          callouts={[
            {
              x: 34.4,
              y: 71.9,
              label:
                "BUY tag — AlphaTrend just crossed above its offset copy near a swing low. Price chops sideways right after; the line holds flat instead of trailing up, which is the ratchet behavior in a weak/uncertain uptrend read.",
            },
            {
              x: 65.9,
              y: 70.5,
              label:
                "SELL tag — the line crosses back below its offset copy after a local high, flipping the read to bearish.",
            },
            {
              x: 16.5,
              y: 37.4,
              label:
                "During the sharp move down, the line sits flat above price acting as resistance — it only steps down further as new lower momentum confirms, it doesn't retrace upward against the move.",
            },
            {
              x: 7.9,
              y: 6.9,
              label:
                "“Volume Based Coloured Bars 21” is a separate companion script (also by KivancOzbilgic) shown alongside AlphaTrend in this example for candle coloring — it's not part of AlphaTrend itself.",
            },
          ]}
          caption="Screenshot of the live example chart on the AlphaTrend script page (tradingview.com/script/o50NYLAZ-AlphaTrend), captured for reference in this journal."
        />
      </Section>

      <Section title="Inputs you can adjust, and why">
        <div className="space-y-4">
          <InputRow name="Coefficient" default="1">
            The ATR multiplier controlling how far the line trails from
            price. Raise it for a wider stop — fewer whipsaws in volatile
            names, but more room given back before you're stopped out. Lower
            it for a tighter trailing stop that reacts faster, at the cost of
            more premature exits in normal volatility.
          </InputRow>
          <InputRow name="Common Period" default="14">
            The shared lookback for ATR and the MFI/RSI momentum filter.
            Shorter reacts to recent volatility and momentum shifts faster
            (more signals, more noise); longer smooths both out, producing
            fewer, later signals. The publisher notes the defaults are tuned
            for daily and 4H charts — worth re-checking on very short
            intraday timeframes.
          </InputRow>
          <InputRow name="Change calculation (no volume data)" default="off">
            Switches the momentum filter from Money Flow Index to RSI. MFI
            needs real volume data, which some CFDs/forex feeds don't
            provide reliably — turn this on for those instruments so the
            momentum read isn't running on bad volume data. Leave it off for
            stocks and crypto with real volume.
          </InputRow>
          <InputRow name="Show Signals" default="on">
            Purely cosmetic — toggles the BUY/SELL labels on the chart.
            Turning it off still leaves the line and its ratchet behavior
            intact; you'd just be reading crosses visually instead.
          </InputRow>
        </div>
      </Section>

      <Section title="How this fits the discipline rules in this journal">
        <p>
          This is the one indicator on this page that maps directly onto{" "}
          <em>position sizing</em>, not just entries. This journal sizes a
          position as risk amount ÷ stop distance — an ATR-based line like
          this gives you a volatility-aware stop distance to plug into that
          formula instead of picking an arbitrary percentage below entry.
          It&apos;s also a legitimate candidate for the &quot;stop not moved
          against the plan&quot; discipline check: if you&apos;re using this
          line as your stop, the ratchet behavior itself enforces that rule —
          it only tightens in your favor, never loosens.
        </p>
      </Section>

      <p className="text-xs text-parchment-faint pt-2 border-t border-line">
        Source:{" "}
        <a
          href="https://www.tradingview.com/script/o50NYLAZ-AlphaTrend/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-gold-bright hover:underline"
        >
          AlphaTrend by KivancOzbilgic on TradingView
        </a>
        . Line/signal diagrams above are original recreations for this
        journal; the chart example is a real screenshot from the
        publisher&apos;s own script page.
      </p>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section className="space-y-3">
      <h2 className="font-display text-xl text-parchment">{title}</h2>
      <div className="space-y-3 text-sm text-parchment-dim leading-relaxed">{children}</div>
    </section>
  );
}

function InputRow({ name, default: defaultValue, children }) {
  return (
    <div className="border-l-2 border-gold-dim pl-3">
      <p className="text-sm text-parchment">
        {name}{" "}
        <span className="font-mono text-xs text-gold-bright">default {defaultValue}</span>
      </p>
      <p className="text-sm text-parchment-dim leading-relaxed mt-0.5">{children}</p>
    </div>
  );
}
